name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get raylib
      run: |
        curl -sSL https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_linux_amd64.tar.gz -o raylib.tar.gz
        tar xf raylib.tar.gz
        rm raylib.tar.gz
        mkdir -p raylib/src
        mv raylib-5.0_linux_amd64/lib/* raylib-5.0_linux_amd64/include/* raylib/src/
        rm -r raylib-5.0_linux_amd64
    - name: configure
      run: cp configs/linux.mk config.mk
    - name: make
      run: make
