name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cc -o build build.c
        ./build
        
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: prepare
      shell: cmd
      # cl.exe isn't available as-is in Github images because they don't want
      # to, so we need to pull env vars ourselves. Refs:
      # https://github.com/actions/runner-images/issues/6205#issuecomment-1241573412
      # https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#create-your-own-command-prompt-shortcut
      run: |
        call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
        cl.exe /out:build.exe build.c
    - name: build
      shell: cmd
      run: |
        call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
        build.exe
